title: Portfolio
author: Sophie Li
email: s.li@outlook.com.au
description: >-
  Sophie Li

social:
  twitter: 
  facebook: 
  instagram: prtcl3x
  github: 
  linkedin: sophie-li-a82987249

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
